services:
  postgres:
    image: postgres:16-alpine
    container_name: kubeatlas-postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: kubeatlas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: kubeatlas-keycloak
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: http://localhost:8081
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    command: [
      "start-dev",
      "--import-realm"
    ]
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kubeatlas-backend
    depends_on:
      - keycloak
      - redis
    environment:
      RUST_LOG: info
      SERVER_ADDRESS: 0.0.0.0:3001
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: kubeatlas
      KEYCLOAK_CLIENT_ID: kubeatlas-backend
      KEYCLOAK_CLIENT_SECRET: backend-secret-key
      ADM_USER: admin-service
      ADM_PASSWORD: AdminPassw0rd!
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      REDIS_URL: redis://redis:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"

volumes:
  postgres_data:
  redis_data:


